import "dotenv/config";
import {
  PrismaClient,
  MuscleGroup,
  TargetGender,
  EquipmentType,
} from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("🏗️ Construindo Biblioteca de 100 Exercícios...");

  const exercises = [
    // 🟦 PEITORAL (CHEST) - 12 Exercícios
    {
      name: "Supino Reto com Barra",
      muscleGroup: MuscleGroup.CHEST,
      equipmentType: EquipmentType.BARBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Supino Reto com Halteres",
      muscleGroup: MuscleGroup.CHEST,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Supino Inclinado com Barra",
      muscleGroup: MuscleGroup.CHEST,
      equipmentType: EquipmentType.BARBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Supino Inclinado com Halteres",
      muscleGroup: MuscleGroup.CHEST,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Supino Declinado com Barra",
      muscleGroup: MuscleGroup.CHEST,
      equipmentType: EquipmentType.BARBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Supino Declinado com Halteres",
      muscleGroup: MuscleGroup.CHEST,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Crucifixo Reto com Halteres",
      muscleGroup: MuscleGroup.CHEST,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Crucifixo Inclinado com Halteres",
      muscleGroup: MuscleGroup.CHEST,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Peck Deck (Voador na Máquina)",
      muscleGroup: MuscleGroup.CHEST,
      equipmentType: EquipmentType.MACHINE_PLATE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Crossover na Polia Alta",
      muscleGroup: MuscleGroup.CHEST,
      equipmentType: EquipmentType.MACHINE_CABLE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Crossover na Polia Baixa",
      muscleGroup: MuscleGroup.CHEST,
      equipmentType: EquipmentType.MACHINE_CABLE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Pullover com Halter",
      muscleGroup: MuscleGroup.CHEST,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },

    // 🟩 COSTAS (BACK) - 14 Exercícios
    {
      name: "Barra Fixa (Pegada Pronada)",
      muscleGroup: MuscleGroup.BACK,
      equipmentType: EquipmentType.BODYWEIGHT,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Barra Fixa (Pegada Supinada/Chin-up)",
      muscleGroup: MuscleGroup.BACK,
      equipmentType: EquipmentType.BODYWEIGHT,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Puxada Alta na Polia (Pegada Pronada)",
      muscleGroup: MuscleGroup.BACK,
      equipmentType: EquipmentType.MACHINE_CABLE,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Puxada Alta na Polia (Com Triângulo)",
      muscleGroup: MuscleGroup.BACK,
      equipmentType: EquipmentType.MACHINE_CABLE,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Remada Curvada com Barra (Pegada Pronada)",
      muscleGroup: MuscleGroup.BACK,
      equipmentType: EquipmentType.BARBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Remada Curvada com Barra (Pegada Supinada)",
      muscleGroup: MuscleGroup.BACK,
      equipmentType: EquipmentType.BARBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Remada Unilateral com Halter (Serrote)",
      muscleGroup: MuscleGroup.BACK,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Remada Cavalinho (T-Bar Row com Barra)",
      muscleGroup: MuscleGroup.BACK,
      equipmentType: EquipmentType.BARBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Remada Cavalinho Articulada (Máquina)",
      muscleGroup: MuscleGroup.BACK,
      equipmentType: EquipmentType.MACHINE_PLATE,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Remada Baixa na Polia com Triângulo",
      muscleGroup: MuscleGroup.BACK,
      equipmentType: EquipmentType.MACHINE_CABLE,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Pull Down com Corda na Polia Alta",
      muscleGroup: MuscleGroup.BACK,
      equipmentType: EquipmentType.MACHINE_CABLE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Pull Down com Barra Reta",
      muscleGroup: MuscleGroup.BACK,
      equipmentType: EquipmentType.MACHINE_CABLE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Levantamento Terra (Deadlift)",
      muscleGroup: MuscleGroup.BACK,
      equipmentType: EquipmentType.BARBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Extensão Lombar no Banco (Hiperextensão)",
      muscleGroup: MuscleGroup.BACK,
      equipmentType: EquipmentType.BODYWEIGHT,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },

    // 🟧 OMBROS E TRAPÉZIO (SHOULDERS) - 12 Exercícios
    {
      name: "Desenvolvimento Militar com Barra em Pé",
      muscleGroup: MuscleGroup.SHOULDERS,
      equipmentType: EquipmentType.BARBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Desenvolvimento com Halteres Sentado",
      muscleGroup: MuscleGroup.SHOULDERS,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Desenvolvimento na Máquina Articulada",
      muscleGroup: MuscleGroup.SHOULDERS,
      equipmentType: EquipmentType.MACHINE_PLATE,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Desenvolvimento Arnold com Halteres",
      muscleGroup: MuscleGroup.SHOULDERS,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Elevação Lateral com Halteres",
      muscleGroup: MuscleGroup.SHOULDERS,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Elevação Lateral na Polia Baixa (Cabo)",
      muscleGroup: MuscleGroup.SHOULDERS,
      equipmentType: EquipmentType.MACHINE_CABLE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Elevação Frontal com Barra",
      muscleGroup: MuscleGroup.SHOULDERS,
      equipmentType: EquipmentType.BARBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Elevação Frontal com Halteres",
      muscleGroup: MuscleGroup.SHOULDERS,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Elevação Frontal na Polia com Corda",
      muscleGroup: MuscleGroup.SHOULDERS,
      equipmentType: EquipmentType.MACHINE_CABLE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Crucifixo Inverso com Halteres (Curvado)",
      muscleGroup: MuscleGroup.SHOULDERS,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Crucifixo Inverso no Peck Deck (Máquina)",
      muscleGroup: MuscleGroup.SHOULDERS,
      equipmentType: EquipmentType.MACHINE_PLATE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Encolhimento de Ombros com Halteres",
      muscleGroup: MuscleGroup.SHOULDERS,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },

    // 🟨 BÍCEPS E ANTEBRAÇOS (ARMS) - 12 Exercícios
    {
      name: "Rosca Direta com Barra Reta",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.BARBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Rosca Direta com Barra W",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.BARBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Rosca Alternada com Halteres",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Rosca Martelo com Halteres",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Rosca Martelo na Polia com Corda",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.MACHINE_CABLE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Rosca Scott com Barra W",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.BARBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Rosca Scott na Máquina",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.MACHINE_PLATE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Rosca Concentrada com Halter",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Rosca na Polia Baixa (Com Barra Reta)",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.MACHINE_CABLE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Rosca Inversa com Barra Reta",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.BARBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Flexão de Punho com Barra (Antebraço)",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.BARBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Extensão de Punho com Halteres (Antebraço)",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },

    // 🟪 TRÍCEPS (ARMS) - 10 Exercícios
    {
      name: "Tríceps Pulley com Barra Reta",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.MACHINE_CABLE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Tríceps Pulley com Corda",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.MACHINE_CABLE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Tríceps Pulley Pegada Invertida (Supinada)",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.MACHINE_CABLE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Tríceps Testa com Barra W",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.BARBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Tríceps Testa com Halteres",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Tríceps Francês Unilateral com Halter",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Tríceps Francês Bilateral com Halter",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Tríceps Coice (Kickback) com Halter",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Tríceps Coice na Polia Baixa",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.MACHINE_CABLE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Mergulho nas Paralelas",
      muscleGroup: MuscleGroup.ARMS,
      equipmentType: EquipmentType.BODYWEIGHT,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },

    // 🟥 QUADRÍCEPS (LEGS) - 10 Exercícios
    {
      name: "Agachamento Livre com Barra (Back Squat)",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.BARBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Agachamento Frontal com Barra (Front Squat)",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.BARBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Agachamento no Smith Machine",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.MACHINE_PLATE,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Agachamento Búlgaro com Halteres",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Agachamento Hack (Hack Machine)",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.MACHINE_PLATE,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Leg Press 45º",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.MACHINE_PLATE,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Leg Press Horizontal",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.MACHINE_PLATE,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Cadeira Extensora",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.MACHINE_PLATE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Afundo com Halteres",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Passada (Walking Lunge) com Halteres",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },

    // 🟫 POSTERIORES E GLÚTEOS (LEGS) - 10 Exercícios
    {
      name: "Stiff com Barra",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.BARBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Stiff com Halteres",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Levantamento Terra Romeno (RDL)",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.BARBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Mesa Flexora (Deitado)",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.MACHINE_PLATE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Cadeira Flexora (Sentado)",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.MACHINE_PLATE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Flexora Vertical Unilateral (Em pé)",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.MACHINE_CABLE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Elevação Pélvica com Barra (Hip Thrust)",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.BARBELL,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Elevação Pélvica na Máquina",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.MACHINE_PLATE,
      targetGender: TargetGender.BOTH,
      isCompound: true,
    },
    {
      name: "Cadeira Abdutora",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.MACHINE_PLATE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Glúteo Quatro Apoios na Polia Baixa",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.MACHINE_CABLE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },

    // ⬛ PANTURRILHAS (LEGS) - 5 Exercícios
    {
      name: "Gêmeos em Pé na Máquina",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.MACHINE_PLATE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Gêmeos Sentado na Máquina (Foco no Sóleo)",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.MACHINE_PLATE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Gêmeos no Leg Press 45º",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.MACHINE_PLATE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Gêmeos em Pé no Smith Machine",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.MACHINE_PLATE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Gêmeos Unilateral com Halter (Em um degrau)",
      muscleGroup: MuscleGroup.LEGS,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },

    // ⬜ ABDÔMEN E CORE (CORE) - 15 Exercícios
    {
      name: "Crunch Abdominal Clássico (Solo)",
      muscleGroup: MuscleGroup.CORE,
      equipmentType: EquipmentType.BODYWEIGHT,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Abdominal Supra na Polia com Corda",
      muscleGroup: MuscleGroup.CORE,
      equipmentType: EquipmentType.MACHINE_CABLE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Abdominal Infra no Banco Declinado",
      muscleGroup: MuscleGroup.CORE,
      equipmentType: EquipmentType.BODYWEIGHT,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Abdominal Infra em Suspensão (Pendurado na Barra)",
      muscleGroup: MuscleGroup.CORE,
      equipmentType: EquipmentType.BODYWEIGHT,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Abdominal Infra nas Paralelas",
      muscleGroup: MuscleGroup.CORE,
      equipmentType: EquipmentType.BODYWEIGHT,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Abdominal Remador",
      muscleGroup: MuscleGroup.CORE,
      equipmentType: EquipmentType.BODYWEIGHT,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Abdominal Borboleta (Sit-up)",
      muscleGroup: MuscleGroup.CORE,
      equipmentType: EquipmentType.BODYWEIGHT,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Abdominal Canivete (V-up)",
      muscleGroup: MuscleGroup.CORE,
      equipmentType: EquipmentType.BODYWEIGHT,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Abdominal Russo (Russian Twist) com Peso",
      muscleGroup: MuscleGroup.CORE,
      equipmentType: EquipmentType.DUMBBELL,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Roda Abdominal (Ab Wheel)",
      muscleGroup: MuscleGroup.CORE,
      equipmentType: EquipmentType.BODYWEIGHT,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Prancha Isométrica Tradicional (Solo)",
      muscleGroup: MuscleGroup.CORE,
      equipmentType: EquipmentType.BODYWEIGHT,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Prancha Lateral Isométrica",
      muscleGroup: MuscleGroup.CORE,
      equipmentType: EquipmentType.BODYWEIGHT,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Woodchopper (Lenhador) na Polia Alta",
      muscleGroup: MuscleGroup.CORE,
      equipmentType: EquipmentType.MACHINE_CABLE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Woodchopper (Lenhador) na Polia Baixa",
      muscleGroup: MuscleGroup.CORE,
      equipmentType: EquipmentType.MACHINE_CABLE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
    {
      name: "Abdominal Máquina (Crunch Machine)",
      muscleGroup: MuscleGroup.CORE,
      equipmentType: EquipmentType.MACHINE_PLATE,
      targetGender: TargetGender.BOTH,
      isCompound: false,
    },
  ];

  console.log(`📦 Total de exercícios: ${exercises.length}`);

  for (const ex of exercises) {
    await prisma.exercise.upsert({
      where: { name: ex.name },
      update: {
        equipmentType: ex.equipmentType,
        targetGender: ex.targetGender,
        isCompound: ex.isCompound,
      },
      create: ex,
    });
  }

  console.log("✅ Base Iron-Brain com 100 Exercícios Concluída!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
